apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-operators

bases:
  https://github.com/redhat-cop/gitops-catalog/web-terminal-operator/operator/overlays/fast?ref=main
