apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

resources:
  - ../../base
  # - letsencrypt-aws-sealed-secret.yaml

patches:
  - patch: |-
      - op: replace
        path: /spec/issuerRef/name
        value: letsencrypt-staging
    target:
      kind: Certificate
      name: openshift-api
  - patch: |-
      - op: replace
        path: /spec/issuerRef/name
        value: letsencrypt-staging
    target:
      kind: Certificate
      name: openshift-wildcard
  - patch: |-
      - op: replace
        path: /spec/acme/email
        value: clatschk@redhat.com
      - op: replace
        path: /spec/acme/privateKeySecretRef
        value:
          name: letsencrypt-issuer-account-key
      - op: replace
        path: /spec/acme/solvers/0/dns01/route53/accessKeyID
        value: AKIAQJKWXV7MNZQUCH4P
      # - op: replace
      #   path: /spec/acme/solvers/0/dns01/route53/hostedZoneID
      #   value: Z03493643DMUOB4JH32Q0
      - op: replace
        path: /spec/acme/solvers/0/dns01/route53/region
        value: us-east-1
    target:
      kind: ClusterIssuer
      name: letsencrypt-prod
  - patch: |-
      - op: replace
        path: /spec/acme/email
        value: clatschk@redhat.com
      - op: replace
        path: /spec/acme/privateKeySecretRef
        value:
          name: letsencrypt-issuer-account-key
      - op: replace
        path: /spec/acme/solvers/0/dns01/route53/accessKeyID
        value: AKIAQJKWXV7MNZQUCH4P
      # - op: replace
      #   path: /spec/acme/solvers/0/dns01/route53/hostedZoneID
      #   value: Z03493643DMUOB4JH32Q0
      - op: replace
        path: /spec/acme/solvers/0/dns01/route53/region
        value: us-east-1
    target:
      kind: ClusterIssuer
      name: letsencrypt-staging
