apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simple-sandbox-cleanup
  namespace: openshift-gitops
spec:
  destination:
    namespace: sandbox-cleanup
    server: https://kubernetes.default.svc
  project: cluster-config
  source:
    path: components/simple/sandbox-cleanup
    repoURL: git@github.com:redhat-manufacturing/osdu-lab-gitops.git
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true
