apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

resources:
  - app-local-storage.yaml
  - app-pgadmin4.yaml
  # see applicationset
  # - app-sandbox-cleanup.yaml
