apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: puller-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:image-puller
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: ServiceAccount
  name: puller
