apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pusher-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:image-pusher
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: ServiceAccount
  name: pusher
