apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-gitops

bases:
  - ../default

patches:
  - patch: |-
      - op: add
        path: /users
        value:
          - codekow
    target:
      kind: Group
      name: gitops-admins
  - patch: |-
      - op: replace
        path: /spec/rbac/policy
        value: |
          g, gitops-admins, role:admin
          g, lab-cluster-admins, role:admin
          g, system:cluster-admins, role:admin
          g, cluster-admins, role:admin
      - op: add
        path: /spec/server/route/termination
        value: edge
    target:
      kind: ArgoCD
