apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../../../components/configs/cluster-certs/overlays/letsencrypt

patches:
  - patch: |-
      - op: replace
        path: /spec/dnsNames
        value:
          - api.hou.edgelab.online
    target:
      kind: Certificate
      name: openshift-api
  - patch: |-
      - op: replace
        path: /spec/dnsNames
        value:
          - '*.apps.hou.edgelab.online'
      - op: replace
        path: /spec/commonName
        value: '*.apps.hou.edgelab.online'
    target:
      kind: Certificate
      name: openshift-wildcard
  - patch: |-
      - op: replace
        path: /spec/acme/solvers/0/selector/dnsZones
        value:
          - 'edgelab.online'
          - 'hou.edgelab.online'
      - op: add
        path: /spec/acme/solvers/0/dns01/cnameStrategy
        value: Follow
    target:
      kind: ClusterIssuer
      name: letsencrypt-prod
  - patch: |-
      - op: replace
        path: /spec/acme/solvers/0/selector/dnsZones
        value:
          - 'edgelab.online'
          - 'hou.edgelab.online'
      - op: add
        path: /spec/acme/solvers/0/dns01/cnameStrategy
        value: Follow
    target:
      kind: ClusterIssuer
      name: letsencrypt-staging
