- op: replace
  path: /spec/template/spec/source/repoURL
  value: 'git@github.com:redhat-manufacturing/osdu-lab-gitops.git'
- op: replace
  path: /spec/template/spec/source/targetRevision
  value: main
