apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - app-pgadmin4.yaml
  # - app-sandbox-cleanup.yaml
  - cluster-config-manager-app.yaml
  - cluster-rbac-app.yaml
  - cluster-namespaces-app.yaml
