- op: add
  path: /spec/generators/0/list/elements
  value:
    - cluster: local
      url: https://kubernetes.default.svc
      values:
        name: simple-sandbox-cleanup
        namespace: openshift-gitops
        path: components/simple/sandbox-cleanup
    - cluster: local
      url: https://kubernetes.default.svc
      values:
        name: config-oauth
        path: components/configs/oauth/overlays/default
