apiVersion: local.storage.openshift.io/v1alpha1
kind: LocalVolumeSet
metadata:
  name: autodetect-local
spec:
  nodeSelector:
    nodeSelectorTerms:
      - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - se350-01
              - se350-02
              - se350-03
  storageClassName: local-disks 
  volumeMode: Filesystem
  fsType: xfs
  deviceInclusionSpec:
    deviceTypes: 
      - disk
      # - part
    minSize: 10G
