apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-operators-applicationset
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Prune=false
spec:
  generators:
    - list:
        elements:
        - cluster: local
          url: https://kubernetes.default.svc
          values:
            name: strimzi-operator
            path: components/operators/strimzi/operator/overlays/stable
        - cluster: local
          url: https://kubernetes.default.svc
          values:
            name: cert-manager-operator
            path: components/operators/cert-manager/operator/overlays/tech-preview
        - cluster: local
          url: https://kubernetes.default.svc
          values:
            name: aap-operator
            path: components/operators/ansible-automation-platform/operator/overlays/stable-2.2
        - cluster: local
          url: https://kubernetes.default.svc
          values:
            name: odf-operator
            path: components/operators/openshift-data-foundation/operator/overlays/stable-4.10
        - cluster: local
          url: https://kubernetes.default.svc
          values:
            name: local-storage-operator
            path: components/operators/local-storage/operator/overlays/stable
  template:
    metadata:
      name: '{{values.name}}'
      annotations:
        argocd.argoproj.io/compare-options: IgnoreExtraneous
        argocd.argoproj.io/sync-options: Prune=false
      labels:
        app.kubernetes.io/instance: cluster-config-manager
    spec:
      project: cluster-config
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
        retry:
          limit: 2
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 10m
      source:
        repoURL: git@github.com:redhat-manufacturing/osdu-lab-gitops.git
        targetRevision: main
        path: '{{values.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: openshift-gitops
