# this instance will not progress before you label nodes
# oc label node cluster.ocs.openshift.io/openshift-storage="" --all
#
# oc annotate sc ocs-storagecluster-cephfs storageclass.kubernetes.io/is-default-class: "true"
apiVersion: odf.openshift.io/v1alpha1
kind: StorageSystem
metadata:
  name: ocs-storagecluster-storagesystem
  namespace: openshift-storage
spec:
  kind: storagecluster.ocs.openshift.io/v1
  name: ocs-storagecluster
  namespace: openshift-storage
