apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: archer-admin-rolebinding
  namespace: archer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: jarcher
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: codekow
