- op: add
  path: /spec/identityProviders
  value:
    - github:
        clientID: 3a1b9fd2ada5936b5a75
        clientSecret:
          name: github-client-secret
        hostname: ''
        organizations: []
        teams:
          - redhat-manufacturing/edge-lab
      mappingMethod: claim
      name: GitHub
      type: GitHub
    - name: community.opengroup.org
      mappingMethod: claim
      type: GitLab
      gitlab:
        clientID: bf881f4d354b73f1bcf0abfde1887ad743e4c61447d512f1c595019990d5a082
        clientSecret:
          name: community-gitlab-secret
        url: https://community.opengroup.org
- op: add
  path: /spec/identityProviders/-
  value:
    name: Chevron
    mappingMethod: claim
    type: OpenID
    openID:
      # ca:
      #   name: myapp-oidc-client-ca-cert
      claims:
        email:
          - email
        name:
          - name
        preferredUsername:
          - preferred_username
      clientID: de5bbbac-f86c-4fba-bab8-33061d315d1a
      clientSecret:
        name: azure-oidc-client-secret
      extraScopes: []
      issuer: https://login.microsoftonline.com/fd799da1-bfc1-4234-a91c-72b3a1cb9e26/v2.0
      # callback: https://oauth-openshift.apps.hou.edgelab.online/oauth2callback/Chevron
